name = "amit-photos"
main = "worker.js"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "amit-photos-db"
database_id = "802379c7-97cf-4262-93b8-da81c5c3c07d"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "amit-photos-images"

[[routes]]
pattern = "www.amitphotos.com/*"
zone_name = "amitphotos.com"
